export const perfiles = [
  {
    bg: 'emerald',
    img_src: 'https://media.discordapp.net/attachments/1032516925617614878/1106068911893524490/fi.png?width=458&height=458',
    usuario: 'Anfitrion',
    rareza: 'l',
    desc: 'El creador y líder de Insomnia. Anfitrion siempre trata de darles el mejor contenido posible a los miembros de esta bonita comunidad.',
    discord: 'Anfitrion#0082',
    nacionalidad: 'Peruano',
    edad: '17',
    distinciones: [
      { distincion: 1 },
      { distincion: 3 },
      { distincion: 5 },
      { distincion: 6 },
      { distincion: 7 },
      { distincion: 8 },
      { distincion: 9 },
      { distincion: 10 },
      { distincion: 11 },
    ],
    op: 's'
  },
  {
    bg: 'cyan',
    img_src: 'https://media.discordapp.net/attachments/1032516925617614878/1106068912149368852/nizero.png?width=458&height=458',
    usuario: 'Nic0_Mongrant',
    rareza: 'e',
    desc: 'También conocido como N. Mongrant. No solo es uno de los miembros más activos de Insomnia, sino que también es la mano derecha de Anfitrion y moderador de Insomnia. N. Mongrant construyó gran parte del lobby del servidor amistoso de Minecraft Tecla 3, y mientras Anfitrion estuvo ausente, él jugaba y le daba vida al servidor.',
    discord: 'Niczero_Mongrant#3665',
    nacionalidad: 'Argentino',
    edad: '16',
    distinciones: [
      { distincion: 2 },
      { distincion: 4 },
      { distincion: 9 },
      { distincion: 10 },
      { distincion: 'T2' },
    ],
    op: 's'
  },
  {
    bg: 'red',
    img_src: 'https://media.discordapp.net/attachments/1032516925617614878/1106262852307791892/image.png?width=458&height=458',
    usuario: 'Lenchata',
    rareza: 'e',
    desc: 'Un gran donador y alguna vez administrador de Insomnia. Lenchata se encuentra actualmente inactivo.',
    discord: ' Lenchata#5606',
    nacionalidad: 'Chileno',
    edad: '17',
    distinciones: [
      { distincion: 5 },
      { distincion: 11 },
    ],
    op: 's'
  },
  {
    bg: '',
    img_src: 'https://media.discordapp.net/attachments/1032516925617614878/1106068911654453290/cian.png',
    usuario: 'Caian',
    rareza: 'u',
    desc: 'El argentino más loco y divertido que Insomnia haya concido. Caian siempre aporta gran parte de la diversión en los canales de voz, es buen amigo y leal a Insomnia.',
    discord: 'caian#6161',
    nacionalidad: 'Argentino',
    edad: '14',
    distinciones: [
      { distincion: 8 },
      { distincion: 11 },
      { distincion: 'T2' },
    ],
  },
  {
    bg: '',
    img_src: 'https://media.discordapp.net/attachments/1032516925617614878/1106068912430395452/pena.png?width=458&height=458',
    usuario: 'adrianpeña',
    rareza: 'r',
    desc: 'Peruano de corazón y gran amigo de N. Mongrant. adrianpeña es muy activo y un poquito "pipipi".',
    discord: 'adrianpeña#7645',
    nacionalidad: 'Peruano',
    edad: '14',
    distinciones: [
      { distincion: 'T2' },
    ],
  },
]